### ISSUE TITLE
Building / Running in VS 2015

### ISSUE THREAD

**Issue by chunk78** [lifebeyondfife/Cm93#60]
Hi I'm having trouble getting this to run in Visual Studio 2015.  Is this program able to run in VS2015 or can you point me in the write direction of how I can convert it manually

Thanks

**Comment by lifebeyondfife** [comment]
Hi chunk78,

Not really a day-to-day VS coder to be honest so I'm still running VS2013. I'll have a look tomorrow at work and see if I can upgrade the solution.

Cheers.
Iain

**Comment by lifebeyondfife** [comment]
Had a quick look, but no conclusive fix as yet. Upgrading to the latest System.Data.SQLite.EF6 nuget package got me a little further, but I believe the automated upgrade breaks some of the existing config files.

Will come back to this later but it doesn't look to be trivial.

Thanks for your interest.

**Comment by chunk78** [comment]
Thanks for looking into this .. looking at the screenshots the program looks great and would be ideal way for me to learn more about programming as I was a huge fan of the original championship manager series.

Are you still actively developing this?

**Comment by lifebeyondfife** [comment]
Cheers for the compliment.

I wouldn't say it's being _actively_ worked on, but every few months I'll work on it for a few nights or a solid couple of weeks. I'm focusing on getting a basic version finished now though, rather than trying to get something perfect - it's taken too much of my free time over the past few years.

So it still needs tweaking, there's no computer AI, there are some UI elements I'm going to simplify, and some finishing touches needed. But the main shape of it is there.

I've just finished upgrading the SQLite packages - that could well fix things for VS2015. You might have to build a copy of Cm93.sqlite using the Cm93.DatabaseBootstrap project (which should put the file on your Desktop).

After that, create the directory %appdata%\Cm93 i.e. create Cm93 in your roaming AppData directory. Put Cm93.sqlite in that directory. You should be able to debug Cm93.UI and it will pick up the player database from there.

Apologies for all the "coulds", "shoulds" and "mights". It's been a while getting things working from scratch so there may well be issues on another machine.

Best of luck,
Iain

**Comment by lifebeyondfife** [comment]
One final change put in, and I got the Cm93.DatabaseBootstrap project to create Cm93.sqlite. Putting that file in the AppData subdirectory got Cm93 running as expected using VS2015.

Thanks again for the interest, and hope your programming journey goes well.

**Comment by chunk78** [comment]
Hi lifebeyondfife

Thanks for your efforts I have now managed to build this successfully.  After following the instructions of copying the CM93.sqllite to my appdata folder it now runs too. It seemed to previously fall over stating that the createdatabase function was not supported. Not understanding how the program works meant I didn't really know where to start and without your instruction to manually create the file I still would have been none the wiser.

Now that I have it building and running the fun begins as I try to work out how your program works.

Thanks again for helping me to get this up and running.  I'm looking forward to learning, especially when I have an example of code for something I am interested in.
